//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CpsCouponsSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mall
    {
        public Mall()
        {
            this.Program_Retailer_Selected_Malls = new HashSet<Program_Retailer_Selected_Malls>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string MallCode { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public Nullable<int> StateID { get; set; }
        public string Zip { get; set; }
        public Nullable<System.Guid> HeaderAssetID { get; set; }
        public string HeaderBGColor { get; set; }
        public string FooterHTML { get; set; }
        public int ZoneId { get; set; }
        public string NavButtonColor { get; set; }
        public string NavButtonHighlightColor { get; set; }
        public string NavBGColor { get; set; }
        public string NavTextColor { get; set; }
        public string NavBorderColor { get; set; }
        public bool UsersGetProofEmail { get; set; }
    
        public virtual State State { get; set; }
        public virtual ICollection<Program_Retailer_Selected_Malls> Program_Retailer_Selected_Malls { get; set; }
    }
}
