//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CpsCouponsSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program_Fields
    {
        public Program_Fields()
        {
            this.Program_Field_Values = new HashSet<Program_Field_Values>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ProgramId { get; set; }
    
        public virtual ICollection<Program_Field_Values> Program_Field_Values { get; set; }
        public virtual Program Program { get; set; }
    }
}
