//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CpsCouponsSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public Program()
        {
            this.Program_Fields = new HashSet<Program_Fields>();
            this.Program_Retailers = new HashSet<Program_Retailers>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Disclaimer { get; set; }
        public Nullable<int> CouponWordCount { get; set; }
    
        public virtual ICollection<Program_Fields> Program_Fields { get; set; }
        public virtual ICollection<Program_Retailers> Program_Retailers { get; set; }
    }
}
