//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CpsCouponsSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program_Field_Values
    {
        public int Id { get; set; }
        public int ProgramFieldId { get; set; }
        public int ProgramRetailerId { get; set; }
        public string Value { get; set; }
    
        public virtual Program_Fields Program_Fields { get; set; }
        public virtual Program_Retailers Program_Retailers { get; set; }
    }
}
