//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CpsCouponsSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.Malls = new HashSet<Mall>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public string Abbreviation { get; set; }
    
        public virtual ICollection<Mall> Malls { get; set; }
    }
}
